name = "0x5eal/semver"
version = "0.1.1"
description = "Strongly typed semver (https://semver.org) parser for Luau"
authors = ["Erica Marigold <hi@devcomp.xyz>"]
repository = "https://github.com/0x5eal/semver-luau.git"
license = "MIT"
includes = ["lib", "pesde.toml", "README.md", "LICENSE.md"]

[scripts]
test = ".lune/test"

[target]
environment = "luau"
lib = "lib/init.luau"

[peer_dependencies]
option = { name = "lukadev_0/option", version = "^1.2.0" }
result = { name = "lukadev_0/result", version = "^1.2.0" }

[dev_dependencies]
frktest = { name = "itsfrank/frktest", target = "lune", version = "^0.0.2" }
stylua = { name = "pesde/stylua", version = "^2.0.1", target = "lune" }
luau_lsp = { name = "pesde/luau_lsp", version = "^1.36.0", target = "lune" }

[indices]
default = "https://github.com/daimond113/pesde-index"
staging = "https://git.devcomp.xyz/pesde-staging/index"
