name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pesde
        uses: ./.github/workflows/pesde.yml
        with:
          pesde-token: ${{ secrets.PESDE_TOKEN }}

      - name: Install dependencies
        run: pesde install

      - name: Publish
        run: pesde publish -y
